apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx2
spec:
  replicas: 2ku
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
